### ISSUE TITLE
Kanban Setup Review

### ISSUE THREAD

**Issue by MosDevx** [MosDevx/MovieApiProject#21]
https://github.com/users/MosDevx/projects/7/views/1

Kindly review the above project's Kanban
The team has 2 members.

Thank You

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] [REQUIRED] Good job so far!  You should have sent you a link to the `GitHub issue` that has a link to the `GitHub project` not a `GitHub repo` link but you paste the link on your issue's description your [Github Repository](https://github.com/MosDevx/MovieApiProject) link, change it to [this link](https://github.com/users/MosDevx/projects/7/views/1) 🙏 

![image](https://user-images.githubusercontent.com/63915024/204358272-eb4d5d42-90a3-4804-9bbf-707a596a7928.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Good implementations ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! Please assign all group tasks to both of you or at least one of you regarding the equal amount of work shared rule 🙏 

![image](https://user-images.githubusercontent.com/63915024/204360767-0c35682c-5ba1-4d93-aeb0-56ebae7bbccd.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Qoosim** [comment]
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

-  Kanban board set up correctly. :heavy_check_mark: 
-  15 cards confirmed on the board. :heavy_check_mark: 
-  Tasks properly assigned to the team members. :heavy_check_mark: 

![](https://camo.githubusercontent.com/894d22fdf31aac32d1cd488fc22318df1eea3204fa6d0129c3d61a99f137ce2d/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336b75536f3734345549504a6a634a55456e2f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
